### ISSUE TITLE
install

### ISSUE THREAD

**Issue by mark11119** [NYTimes/nginx-vod-module-docker#9]
How that install on ubuntu?

**Comment by fsouza** [comment]
Hi @mark11119, since this is a Docker image and not the module itself, running on Ubuntu is the same as running anywhere, provided you have Docker installed.

Now, if you want to install the module itself on Ubuntu, I'd recommend checking the docs for the module: https://github.com/kaltura/nginx-vod-module#debianubuntu-deb-package
